package com.hackucla.chatbot;

/**
 * Created by nkansal on 2/25/17.
 */

/**
 * This class models a request sent to the chat bot. Gson will convert this to JSON for us when we
 * send a request. Fields set to null will not be sent unless specified.
 */
public class ChatBotRequest {
    /**
     * user: API_USER
     * key: API_KEY
     * nick: the nickname of the chat bot to talk to
     * text: the actual text to send the chat bot
     */
    public String user;
    public String key;
    public String nick = null;
    public String text = null;

    /**
     * Use this constructor if we're creating a chat bot. The nickname will be generated by
     * the API and provided in the ChatBotInstance.
     *
     * @param user   API_USER
     * @param key    API_KEY
     */
    public ChatBotRequest(String user, String key) {
        this.user = user;
        this.key = key;
    }

    /**
     * Use this constructor if we're sending a message to an existing chat bot, identified with
     * the "nick" field. The response from the chat bot is serialized in a ChatBotResponse.
     *
     * @param user  API_USER
     * @param key   API_KEY
     * @param nick  The nickname of the chat bot to send the message to
     * @param text  The message to send to the chat bot
     */
    public ChatBotRequest(String user, String key, String nick, String text) {
        this.user = user;
        this.key = key;
        this.nick = nick;
        this.text = text;
    }
}
